name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master
      - run: yarn --prefer-offline
      - run: yarn nx workspace-lint
      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=build-storybook --parallel=3
      - run: yarn nx affected --target=test --parallel=3

  deploy-storybook:
    if: github.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master
      - run: yarn --prefer-offline
      - run: yarn nx affected --target=build-storybook --parallel=3
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: dist/storybook
          CLEAN: true
          TARGET_FOLDER: docs
