name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install
      - run: yarn nx build react-forms
      - run: npm publish --dry-run
        working-directory: dist/packages/react-forms
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
