name: Publish @heetch/cypress-mock-openapi
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install
      - run: yarn nx build cypress-mock-openapi
      - run: npm publish --access public
        working-directory: dist/packages/cypress-mock-openapi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
